<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NhaTaiTro;

class NhaTaiTroSeeder extends Seeder
{
    public function run(): void
    {
        $nhaTaiTros = [
            [
                'ten_nha_tai_tro'        => 'Razer',
                'logo'                   => 'uploads/nha_tai_tros/razer.png',
                'ten_nguoi_dai_dien'     => 'Nguyễn Văn Phúc',
                'so_dien_thoai_dai_dien' => '0281234567',
                'email_dai_dien'         => 'partner.vn@razer.com',
                'website'                => 'https://www.razer.com',
                'mo_ta'                  => 'Thương hiệu thiết bị gaming hàng đầu thế giới.',
            ],
            [
                'ten_nha_tai_tro'        => 'Logitech G',
                'logo'                   => 'uploads/nha_tai_tros/logitech.png',
                'ten_nguoi_dai_dien'     => 'Trần Thị Hương',
                'so_dien_thoai_dai_dien' => '0289876543',
                'email_dai_dien'         => 'gaming.vn@logitech.com',
                'website'                => 'https://www.logitechg.com',
                'mo_ta'                  => 'Nhà sản xuất thiết bị gaming và phụ kiện máy tính uy tín.',
            ],
            [
                'ten_nha_tai_tro'        => 'Red Bull',
                'logo'                   => 'uploads/nha_tai_tros/redbull.png',
                'ten_nguoi_dai_dien'     => 'Lê Minh Tuấn',
                'so_dien_thoai_dai_dien' => '0245678901',
                'email_dai_dien'         => 'esport@redbull.vn',
                'website'                => 'https://www.redbull.com/vn',
                'mo_ta'                  => 'Thương hiệu nước tăng lực tài trợ nhiều sự kiện esport lớn.',
            ],
            [
                'ten_nha_tai_tro'        => 'Samsung Việt Nam',
                'logo'                   => 'uploads/nha_tai_tros/samsung.png',
                'ten_nguoi_dai_dien'     => 'Phạm Hữu Đạt',
                'so_dien_thoai_dai_dien' => '0256789012',
                'email_dai_dien'         => 'b2b@samsung.vn',
                'website'                => 'https://www.samsung.com/vn',
                'mo_ta'                  => 'Tập đoàn công nghệ hàng đầu tài trợ màn hình và thiết bị gaming.',
            ],
            [
                'ten_nha_tai_tro'        => 'Viettel Gaming',
                'logo'                   => 'uploads/nha_tai_tros/viettel.png',
                'ten_nguoi_dai_dien'     => 'Hoàng Quốc Bảo',
                'so_dien_thoai_dai_dien' => '0267890123',
                'email_dai_dien'         => 'gaming@viettel.vn',
                'website'                => 'https://gaming.viettel.vn',
                'mo_ta'                  => 'Nền tảng gaming và esport của tập đoàn viễn thông Viettel.',
            ],
            [
                'ten_nha_tai_tro'        => 'Intel',
                'logo'                   => 'uploads/nha_tai_tros/intel.png',
                'ten_nguoi_dai_dien'     => 'Nguyễn Hoàng Nam',
                'so_dien_thoai_dai_dien' => '0278123456',
                'email_dai_dien'         => 'partner.vn@intel.com',
                'website'                => 'https://www.intel.com',
                'mo_ta'                  => 'Nhà sản xuất bộ vi xử lý và công nghệ máy tính hàng đầu thế giới.',
            ],
            [
                'ten_nha_tai_tro'        => 'NVIDIA',
                'logo'                   => 'uploads/nha_tai_tros/nvidia.png',
                'ten_nguoi_dai_dien'     => 'Trần Minh Khoa',
                'so_dien_thoai_dai_dien' => '0278123457',
                'email_dai_dien'         => 'vn@nvidia.com',
                'website'                => 'https://www.nvidia.com',
                'mo_ta'                  => 'Thương hiệu card đồ họa nổi tiếng, đồng hành cùng nhiều giải đấu Esports.',
            ],
            [
                'ten_nha_tai_tro'        => 'ASUS Republic of Gamers',
                'logo'                   => 'uploads/nha_tai_tros/asus_rog.png',
                'ten_nguoi_dai_dien'     => 'Phạm Quốc Anh',
                'so_dien_thoai_dai_dien' => '0278123458',
                'email_dai_dien'         => 'rog.vn@asus.com',
                'website'                => 'https://rog.asus.com',
                'mo_ta'                  => 'Thương hiệu laptop và linh kiện gaming cao cấp.',
            ],
            [
                'ten_nha_tai_tro'        => 'MSI',
                'logo'                   => 'uploads/nha_tai_tros/msi.png',
                'ten_nguoi_dai_dien'     => 'Lê Thanh Bình',
                'so_dien_thoai_dai_dien' => '0278123459',
                'email_dai_dien'         => 'marketing.vn@msi.com',
                'website'                => 'https://www.msi.com',
                'mo_ta'                  => 'Nhà sản xuất phần cứng máy tính và laptop gaming nổi tiếng.',
            ],
            [
                'ten_nha_tai_tro'        => 'Acer Predator',
                'logo'                   => 'uploads/nha_tai_tros/acer_predator.png',
                'ten_nguoi_dai_dien'     => 'Đỗ Minh Thành',
                'so_dien_thoai_dai_dien' => '0278123460',
                'email_dai_dien'         => 'predator.vn@acer.com',
                'website'                => 'https://www.acer.com/predator',
                'mo_ta'                  => 'Dòng sản phẩm gaming của Acer tài trợ nhiều giải đấu Esports.',
            ],
            [
                'ten_nha_tai_tro'        => 'HyperX',
                'logo'                   => 'uploads/nha_tai_tros/hyperx.png',
                'ten_nguoi_dai_dien'     => 'Vũ Hải Long',
                'so_dien_thoai_dai_dien' => '0278123461',
                'email_dai_dien'         => 'support.vn@hyperx.com',
                'website'                => 'https://hyperx.com',
                'mo_ta'                  => 'Thương hiệu tai nghe, bàn phím và phụ kiện gaming chuyên nghiệp.',
            ],
            [
                'ten_nha_tai_tro'        => 'SteelSeries',
                'logo'                   => 'uploads/nha_tai_tros/steelseries.png',
                'ten_nguoi_dai_dien'     => 'Nguyễn Quốc Minh',
                'so_dien_thoai_dai_dien' => '0288123001',
                'email_dai_dien'         => 'vn@steelseries.com',
                'website'                => 'https://steelseries.com',
                'mo_ta'                  => 'Thương hiệu chuột, bàn phím và tai nghe gaming cao cấp.',
            ],
            [
                'ten_nha_tai_tro'        => 'Corsair',
                'logo'                   => 'uploads/nha_tai_tros/corsair.png',
                'ten_nguoi_dai_dien'     => 'Lê Văn Hùng',
                'so_dien_thoai_dai_dien' => '0288123002',
                'email_dai_dien'         => 'vn@corsair.com',
                'website'                => 'https://www.corsair.com',
                'mo_ta'                  => 'Nhà sản xuất linh kiện và thiết bị gaming nổi tiếng.',
            ],
            [
                'ten_nha_tai_tro'        => 'Kingston FURY',
                'logo'                   => 'uploads/nha_tai_tros/kingston.png',
                'ten_nguoi_dai_dien'     => 'Trần Minh Hải',
                'so_dien_thoai_dai_dien' => '0288123003',
                'email_dai_dien'         => 'vn@kingston.com',
                'website'                => 'https://www.kingston.com',
                'mo_ta'                  => 'Thương hiệu RAM và SSD hiệu năng cao.',
            ],
            [
                'ten_nha_tai_tro'        => 'Gigabyte AORUS',
                'logo'                   => 'uploads/nha_tai_tros/gigabyte_aorus.png',
                'ten_nguoi_dai_dien'     => 'Phạm Anh Tuấn',
                'so_dien_thoai_dai_dien' => '0288123004',
                'email_dai_dien'         => 'vn@gigabyte.com',
                'website'                => 'https://www.aorus.com',
                'mo_ta'                  => 'Thương hiệu bo mạch chủ và laptop gaming.',
            ],
            [
                'ten_nha_tai_tro'        => 'ZOWIE',
                'logo'                   => 'uploads/nha_tai_tros/zowie.png',
                'ten_nguoi_dai_dien'     => 'Hoàng Đức Long',
                'so_dien_thoai_dai_dien' => '0288123005',
                'email_dai_dien'         => 'vn@zowie.com',
                'website'                => 'https://zowie.benq.com',
                'mo_ta'                  => 'Thiết bị gaming chuyên cho tuyển thủ Esports.',
            ],
            [
                'ten_nha_tai_tro'        => 'ViewSonic',
                'logo'                   => 'uploads/nha_tai_tros/viewsonic.png',
                'ten_nguoi_dai_dien'     => 'Đặng Thanh Phong',
                'so_dien_thoai_dai_dien' => '0288123006',
                'email_dai_dien'         => 'vn@viewsonic.com',
                'website'                => 'https://www.viewsonic.com',
                'mo_ta'                  => 'Nhà sản xuất màn hình gaming.',
            ],
            [
                'ten_nha_tai_tro'        => 'BenQ',
                'logo'                   => 'uploads/nha_tai_tros/benq.png',
                'ten_nguoi_dai_dien'     => 'Võ Minh Khang',
                'so_dien_thoai_dai_dien' => '0288123007',
                'email_dai_dien'         => 'vn@benq.com',
                'website'                => 'https://www.benq.com',
                'mo_ta'                  => 'Màn hình và máy chiếu chất lượng cao.',
            ],
            [
                'ten_nha_tai_tro'        => 'Secretlab',
                'logo'                   => 'uploads/nha_tai_tros/secretlab.png',
                'ten_nguoi_dai_dien'     => 'Ngô Văn Phát',
                'so_dien_thoai_dai_dien' => '0288123008',
                'email_dai_dien'         => 'vn@secretlab.co',
                'website'                => 'https://secretlab.co',
                'mo_ta'                  => 'Thương hiệu ghế gaming cao cấp.',
            ],
            [
                'ten_nha_tai_tro'        => 'Alienware',
                'logo'                   => 'uploads/nha_tai_tros/alienware.png',
                'ten_nguoi_dai_dien'     => 'Đỗ Thành Công',
                'so_dien_thoai_dai_dien' => '0288123009',
                'email_dai_dien'         => 'vn@alienware.com',
                'website'                => 'https://www.alienware.com',
                'mo_ta'                  => 'Laptop và PC gaming hiệu năng cao.',
            ],
            [
                'ten_nha_tai_tro'        => 'Dell Technologies',
                'logo'                   => 'uploads/nha_tai_tros/dell.png',
                'ten_nguoi_dai_dien'     => 'Lý Quốc Bảo',
                'so_dien_thoai_dai_dien' => '0288123010',
                'email_dai_dien'         => 'vn@dell.com',
                'website'                => 'https://www.dell.com',
                'mo_ta'                  => 'Tập đoàn công nghệ tài trợ hạ tầng và thiết bị.',
            ],
            [
                'ten_nha_tai_tro'        => 'AMD',
                'logo'                   => 'uploads/nha_tai_tros/amd.png',
                'ten_nguoi_dai_dien'     => 'Huỳnh Minh Nhật',
                'so_dien_thoai_dai_dien' => '0288123011',
                'email_dai_dien'         => 'vn@amd.com',
                'website'                => 'https://www.amd.com',
                'mo_ta'                  => 'Nhà sản xuất CPU và GPU hàng đầu.',
            ],
            [
                'ten_nha_tai_tro'        => 'Cooler Master',
                'logo'                   => 'uploads/nha_tai_tros/coolermaster.png',
                'ten_nguoi_dai_dien'     => 'Phan Hoài Nam',
                'so_dien_thoai_dai_dien' => '0288123012',
                'email_dai_dien'         => 'vn@coolermaster.com',
                'website'                => 'https://www.coolermaster.com',
                'mo_ta'                  => 'Thiết bị và phụ kiện máy tính cho game thủ.',
            ],
            [
                'ten_nha_tai_tro'        => 'AOC Gaming',
                'logo'                   => 'uploads/nha_tai_tros/aoc.png',
                'ten_nguoi_dai_dien'     => 'Trịnh Quang Huy',
                'so_dien_thoai_dai_dien' => '0288123013',
                'email_dai_dien'         => 'vn@aoc.com',
                'website'                => 'https://www.aoc.com',
                'mo_ta'                  => 'Thương hiệu màn hình gaming nổi tiếng.',
            ],
        ];

        foreach ($nhaTaiTros as $ntt) {
            $ntt['logo'] = 'https://api.dicebear.com/7.x/initials/svg?seed=' . urlencode($ntt['ten_nha_tai_tro']);
            NhaTaiTro::create($ntt);
        }
    }
}
