<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TuyenThu;

class TuyenThuSeeder extends Seeder
{
    public function run(): void
    {
        $tuyenThus = [
            // --- Đội 1: Cerberus Esports (CES) ---
            [
                'id_doi_tuyen'   => 1,
                'ho_va_ten'      => 'Nguyễn Đăng Khoa',
                'nickname'       => 'Pun',
                'ngay_sinh'      => '2002-05-14',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'pun@cerberus.vn',
                'so_dien_thoai'  => '0912000101',
                'anh_dai_dien'   => 'uploads/tuyen_thus/pun.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 1,
                'ho_va_ten'      => 'Nguyễn Hữu Phát',
                'nickname'       => 'Ikigai',
                'ngay_sinh'      => '2003-08-20',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'ikigai@cerberus.vn',
                'so_dien_thoai'  => '0912000102',
                'anh_dai_dien'   => 'uploads/tuyen_thus/ikigai.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 1,
                'ho_va_ten'      => 'Lê Trần Quang Hải',
                'nickname'       => 'Richard',
                'ngay_sinh'      => '2001-11-30',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'richard@cerberus.vn',
                'so_dien_thoai'  => '0912000103',
                'anh_dai_dien'   => 'uploads/tuyen_thus/richard.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 1,
                'ho_va_ten'      => 'Trần Đức Lương',
                'nickname'       => 'Hieu3',
                'ngay_sinh'      => '2000-02-15',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'hieu3@cerberus.vn',
                'so_dien_thoai'  => '0912000104',
                'anh_dai_dien'   => 'uploads/tuyen_thus/hieu3.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 1,
                'ho_va_ten'      => 'Nguyễn Hoàng Hải',
                'nickname'       => 'Yushin',
                'ngay_sinh'      => '2002-12-05',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'yushin@cerberus.vn',
                'so_dien_thoai'  => '0912000105',
                'anh_dai_dien'   => 'uploads/tuyen_thus/yushin.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 2: Saigon Buffalo (SGB) ---
            [
                'id_doi_tuyen'   => 2,
                'ho_va_ten'      => 'Lâm Huỳnh Gia Huy',
                'nickname'       => 'CoExist',
                'ngay_sinh'      => '2003-01-10',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'coexist@sgb.vn',
                'so_dien_thoai'  => '0912000201',
                'anh_dai_dien'   => 'uploads/tuyen_thus/coexist.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 2,
                'ho_va_ten'      => 'Trần Văn Chính',
                'nickname'       => 'Gury',
                'ngay_sinh'      => '2002-09-15',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'gury@sgb.vn',
                'so_dien_thoai'  => '0912000202',
                'anh_dai_dien'   => 'uploads/tuyen_thus/gury.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 2,
                'ho_va_ten'      => 'Nguyễn Lộc Phát',
                'nickname'       => 'Froggy',
                'ngay_sinh'      => '2001-04-18',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'froggy@sgb.vn',
                'so_dien_thoai'  => '0912000203',
                'anh_dai_dien'   => 'uploads/tuyen_thus/froggy.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 2,
                'ho_va_ten'      => 'Nguyễn Văn Huy',
                'nickname'       => 'Shogun',
                'ngay_sinh'      => '2003-12-30',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'shogun@sgb.vn',
                'so_dien_thoai'  => '0912000204',
                'anh_dai_dien'   => 'uploads/tuyen_thus/shogun.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 2,
                'ho_va_ten'      => 'Đinh Anh Tài',
                'nickname'       => 'Taki',
                'ngay_sinh'      => '2003-06-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'taki@sgb.vn',
                'so_dien_thoai'  => '0912000205',
                'anh_dai_dien'   => 'uploads/tuyen_thus/taki.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 3: Vikings Esports (VKE) ---
            [
                'id_doi_tuyen'   => 3,
                'ho_va_ten'      => 'Lương Hải Đăng',
                'nickname'       => 'Nana',
                'ngay_sinh'      => '2004-03-22',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'nana@vikings.vn',
                'so_dien_thoai'  => '0912000301',
                'anh_dai_dien'   => 'uploads/tuyen_thus/nana.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 3,
                'ho_va_ten'      => 'Nguyễn Vũ Minh',
                'nickname'       => 'Tomrio',
                'ngay_sinh'      => '2003-10-18',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'tomrio@vikings.vn',
                'so_dien_thoai'  => '0912000302',
                'anh_dai_dien'   => 'uploads/tuyen_thus/tomrio.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 3,
                'ho_va_ten'      => 'Lê Văn Chính',
                'nickname'       => 'Kati',
                'ngay_sinh'      => '2000-09-22',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'kati@vikings.vn',
                'so_dien_thoai'  => '0912000303',
                'anh_dai_dien'   => 'uploads/tuyen_thus/kati.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 3,
                'ho_va_ten'      => 'Hứa Xuân Trung',
                'nickname'       => 'Shogun2',
                'ngay_sinh'      => '2002-11-20',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'shogun2@vikings.vn',
                'so_dien_thoai'  => '0912000304',
                'anh_dai_dien'   => 'uploads/tuyen_thus/shogun2.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 3,
                'ho_va_ten'      => 'Nguyễn Tấn Đạt',
                'nickname'       => 'Slay',
                'ngay_sinh'      => '2000-05-02',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'slay@vikings.vn',
                'so_dien_thoai'  => '0912000305',
                'anh_dai_dien'   => 'uploads/tuyen_thus/slay.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 4: MGN Blue Esports (MBE) ---
            [
                'id_doi_tuyen'   => 4,
                'ho_va_ten'      => 'Đinh Văn Tuấn',
                'nickname'       => 'Ryuk',
                'ngay_sinh'      => '2004-01-14',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'ryuk@mgn.vn',
                'so_dien_thoai'  => '0912000401',
                'anh_dai_dien'   => 'uploads/tuyen_thus/ryuk.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 4,
                'ho_va_ten'      => 'Nguyễn Quốc Vinh',
                'nickname'       => 'Sorn',
                'ngay_sinh'      => '2000-11-20',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'sorn@mgn.vn',
                'so_dien_thoai'  => '0912000402',
                'anh_dai_dien'   => 'uploads/tuyen_thus/sorn.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 4,
                'ho_va_ten'      => 'Phạm Văn Nam',
                'nickname'       => 'Nugu',
                'ngay_sinh'      => '2003-03-10',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'nugu@mgn.vn',
                'so_dien_thoai'  => '0912000403',
                'anh_dai_dien'   => 'uploads/tuyen_thus/nugu.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 4,
                'ho_va_ten'      => 'Võ Văn Thịnh',
                'nickname'       => 'Style',
                'ngay_sinh'      => '2001-08-11',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'style@mgn.vn',
                'so_dien_thoai'  => '0912000404',
                'anh_dai_dien'   => 'uploads/tuyen_thus/style.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 4,
                'ho_va_ten'      => 'Lê Văn Nam',
                'nickname'       => 'Zodiac',
                'ngay_sinh'      => '2002-09-08',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'zodiac@mgn.vn',
                'so_dien_thoai'  => '0912000405',
                'anh_dai_dien'   => 'uploads/tuyen_thus/zodiac.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 5: GAM Esports (GAM) ---
            [
                'id_doi_tuyen'   => 5,
                'ho_va_ten'      => 'Trần Duy Sang',
                'nickname'       => 'Kiaya',
                'ngay_sinh'      => '2001-05-17',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'kiaya@gam.vn',
                'so_dien_thoai'  => '0912000501',
                'anh_dai_dien'   => 'uploads/tuyen_thus/kiaya.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 5,
                'ho_va_ten'      => 'Đỗ Duy Khánh',
                'nickname'       => 'Levi',
                'ngay_sinh'      => '1997-11-21',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'levi@gam.vn',
                'so_dien_thoai'  => '0912000502',
                'anh_dai_dien'   => 'uploads/tuyen_thus/levi.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 5,
                'ho_va_ten'      => 'Nguyễn Duy Cường',
                'nickname'       => 'Emo',
                'ngay_sinh'      => '2003-04-18',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'emo@gam.vn',
                'so_dien_thoai'  => '0912000503',
                'anh_dai_dien'   => 'uploads/tuyen_thus/emo.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 5,
                'ho_va_ten'      => 'Phan Huy Phong',
                'nickname'       => 'EasyLove',
                'ngay_sinh'      => '1999-02-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'easylove@gam.vn',
                'so_dien_thoai'  => '0912000504',
                'anh_dai_dien'   => 'uploads/tuyen_thus/easylove.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 5,
                'ho_va_ten'      => 'Hứa Xuân Trung',
                'nickname'       => 'Elio',
                'ngay_sinh'      => '2001-09-08',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'elio@gam.vn',
                'so_dien_thoai'  => '0912000505',
                'anh_dai_dien'   => 'uploads/tuyen_thus/elio.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 6: Team Whales (TW) ---
            [
                'id_doi_tuyen'   => 6,
                'ho_va_ten'      => 'Nguyễn Vũ Hoàng',
                'nickname'       => 'Sparda',
                'ngay_sinh'      => '2002-03-24',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'sparda@teamwhales.vn',
                'so_dien_thoai'  => '0912000601',
                'anh_dai_dien'   => 'uploads/tuyen_thus/sparda.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 6,
                'ho_va_ten'      => 'Trần Quang Hưng',
                'nickname'       => 'BeanJ',
                'ngay_sinh'      => '2003-01-15',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'beanj@teamwhales.vn',
                'so_dien_thoai'  => '0912000602',
                'anh_dai_dien'   => 'uploads/tuyen_thus/beanj.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 6,
                'ho_va_ten'      => 'Lê Ngọc Đức',
                'nickname'       => 'Gloryy',
                'ngay_sinh'      => '2002-07-20',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'gloryy@teamwhales.vn',
                'so_dien_thoai'  => '0912000603',
                'anh_dai_dien'   => 'uploads/tuyen_thus/gloryy.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 6,
                'ho_va_ten'      => 'Nguyễn Hoàng Lộc',
                'nickname'       => 'Artemis',
                'ngay_sinh'      => '2001-10-05',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'artemis@teamwhales.vn',
                'so_dien_thoai'  => '0912000604',
                'anh_dai_dien'   => 'uploads/tuyen_thus/artemis.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 6,
                'ho_va_ten'      => 'Lê Nguyễn Hoàng',
                'nickname'       => 'Bie',
                'ngay_sinh'      => '2000-09-30',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'bie@teamwhales.vn',
                'so_dien_thoai'  => '0912000605',
                'anh_dai_dien'   => 'uploads/tuyen_thus/bie.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 7: Team Flash (FL) ---
            [
                'id_doi_tuyen'   => 7,
                'ho_va_ten'      => 'Lê Văn Hoàng',
                'nickname'       => 'Yoshino',
                'ngay_sinh'      => '2000-08-14',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'yoshino@teamflash.vn',
                'so_dien_thoai'  => '0912000701',
                'anh_dai_dien'   => 'uploads/tuyen_thus/yoshino.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 7,
                'ho_va_ten'      => 'Hoàng Nguyễn Sơn',
                'nickname'       => 'Draktharr',
                'ngay_sinh'      => '2003-05-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'draktharr@teamflash.vn',
                'so_dien_thoai'  => '0912000702',
                'anh_dai_dien'   => 'uploads/tuyen_thus/draktharr.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 7,
                'ho_va_ten'      => 'Nguyễn Quốc Phong',
                'nickname'       => 'Jane',
                'ngay_sinh'      => '2002-12-22',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'jane@teamflash.vn',
                'so_dien_thoai'  => '0912000703',
                'anh_dai_dien'   => 'uploads/tuyen_thus/jane.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 7,
                'ho_va_ten'      => 'Trịnh Gia Huy',
                'nickname'       => 'Puddin',
                'ngay_sinh'      => '2004-10-18',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'puddin@teamflash.vn',
                'so_dien_thoai'  => '0912000704',
                'anh_dai_dien'   => 'uploads/tuyen_thus/puddin.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 7,
                'ho_va_ten'      => 'Vũ Hoàng Phong',
                'nickname'       => 'Slayder Support',
                'ngay_sinh'      => '2000-11-25',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'slaydersp@teamflash.vn',
                'so_dien_thoai'  => '0912000705',
                'anh_dai_dien'   => 'uploads/tuyen_thus/slaydersp.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 8: Rainbow Warriors (RW) ---
            [
                'id_doi_tuyen'   => 8,
                'ho_va_ten'      => 'Bùi Đức Anh',
                'nickname'       => '2T',
                'ngay_sinh'      => '2001-10-11',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => '2t@rainbow.vn',
                'so_dien_thoai'  => '0912000801',
                'anh_dai_dien'   => 'uploads/tuyen_thus/2t.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 8,
                'ho_va_ten'      => 'Lê Quốc Bảo',
                'nickname'       => 'Spot',
                'ngay_sinh'      => '1999-07-27',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'spot@rainbow.vn',
                'so_dien_thoai'  => '0912000802',
                'anh_dai_dien'   => 'uploads/tuyen_thus/spot.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 8,
                'ho_va_ten'      => 'Vũ Hoàng Phong',
                'nickname'       => 'Artifact2',
                'ngay_sinh'      => '2000-05-19',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'artifact2@rainbow.vn',
                'so_dien_thoai'  => '0912000803',
                'anh_dai_dien'   => 'uploads/tuyen_thus/artifact2.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 8,
                'ho_va_ten'      => 'Phạm Văn Nam',
                'nickname'       => 'EasyLove2',
                'ngay_sinh'      => '1999-02-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'easylove2@rainbow.vn',
                'so_dien_thoai'  => '0912000804',
                'anh_dai_dien'   => 'uploads/tuyen_thus/easylove2.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 8,
                'ho_va_ten'      => 'Nguyễn Hải Phong',
                'nickname'       => 'H3u',
                'ngay_sinh'      => '2001-09-08',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'h3u@rainbow.vn',
                'so_dien_thoai'  => '0912000805',
                'anh_dai_dien'   => 'uploads/tuyen_thus/h3u.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 9: Luxury Esports (LX) ---
            [
                'id_doi_tuyen'   => 9,
                'ho_va_ten'      => 'Nguyễn Quốc Vinh',
                'nickname'       => 'Cozi',
                'ngay_sinh'      => '2003-06-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'cozi@luxury.vn',
                'so_dien_thoai'  => '0912000901',
                'anh_dai_dien'   => 'uploads/tuyen_thus/cozi.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 9,
                'ho_va_ten'      => 'Trần Thanh Sơn',
                'nickname'       => 'Killer1',
                'ngay_sinh'      => '2002-04-09',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'killer1@luxury.vn',
                'so_dien_thoai'  => '0912000902',
                'anh_dai_dien'   => 'uploads/tuyen_thus/killer1.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 9,
                'ho_va_ten'      => 'Lê Minh Quân',
                'nickname'       => 'Blazes',
                'ngay_sinh'      => '2001-08-19',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'blazes@luxury.vn',
                'so_dien_thoai'  => '0912000903',
                'anh_dai_dien'   => 'uploads/tuyen_thus/blazes.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 9,
                'ho_va_ten'      => 'Lý Hoàng Nam',
                'nickname'       => 'Shine',
                'ngay_sinh'      => '2000-12-15',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'shine@luxury.vn',
                'so_dien_thoai'  => '0912000904',
                'anh_dai_dien'   => 'uploads/tuyen_thus/shine.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 9,
                'ho_va_ten'      => 'Đặng Văn Tài',
                'nickname'       => 'Hea',
                'ngay_sinh'      => '2002-10-01',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'hea@luxury.vn',
                'so_dien_thoai'  => '0912000905',
                'anh_dai_dien'   => 'uploads/tuyen_thus/hea.png',
                'trang_thai'     => 1,
            ],

            // --- Đội 10: Team Secret (TS) ---
            [
                'id_doi_tuyen'   => 10,
                'ho_va_ten'      => 'Nguyễn Hoàng Nam',
                'nickname'       => 'Hiro',
                'ngay_sinh'      => '2001-09-14',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Top',
                'email'          => 'hiro@secret.vn',
                'so_dien_thoai'  => '09120001001',
                'anh_dai_dien'   => 'uploads/tuyen_thus/hiro.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 10,
                'ho_va_ten'      => 'Võ Quốc Hưng',
                'nickname'       => 'Quill',
                'ngay_sinh'      => '2002-10-01',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Jungle',
                'email'          => 'quill@secret.vn',
                'so_dien_thoai'  => '09120001002',
                'anh_dai_dien'   => 'uploads/tuyen_thus/quill.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 10,
                'ho_va_ten'      => 'Trần Nhật Nam',
                'nickname'       => 'Aress',
                'ngay_sinh'      => '2004-03-20',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Mid',
                'email'          => 'aress@secret.vn',
                'so_dien_thoai'  => '09120001003',
                'anh_dai_dien'   => 'uploads/tuyen_thus/aress.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 10,
                'ho_va_ten'      => 'Lê Gia Huy',
                'nickname'       => 'Taki2',
                'ngay_sinh'      => '2003-06-12',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'AD Carry',
                'email'          => 'taki2@secret.vn',
                'so_dien_thoai'  => '09120001004',
                'anh_dai_dien'   => 'uploads/tuyen_thus/taki2.png',
                'trang_thai'     => 1,
            ],
            [
                'id_doi_tuyen'   => 10,
                'ho_va_ten'      => 'Nguyễn Minh Khôi',
                'nickname'       => 'Palette2',
                'ngay_sinh'      => '2001-08-03',
                'gioi_tinh'      => 'Nam',
                'quoc_tich'      => 'Việt Nam',
                'vi_tri_thi_dau' => 'Support',
                'email'          => 'palette2@secret.vn',
                'so_dien_thoai'  => '09120001005',
                'anh_dai_dien'   => 'uploads/tuyen_thus/palette2.png',
                'trang_thai'     => 1,
            ],
        ];

        foreach ($tuyenThus as $key => $tt) {
            $tt['anh_dai_dien'] = 'https://i.pravatar.cc/150?u=' . urlencode($tt['nickname']);
            if ($key % 5 == 0) {
                $tt['trang_thai'] = 0;
            }
            TuyenThu::create($tt);
        }
    }
}
